import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))

from filters import (
    DocumentClassifier,
    Decision,
    Deduplicator,
    clean_gutenberg_text,
    classify_book_type,
)


def test_valid_python_source():
    text = """
def hello_world():
    print("Hello, world!")
    return True
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(text, path="hello.py")
    assert decision == Decision.KEEP_CODE


def test_valid_tutorial_prose():
    text = """
# Introduction to Python
Python is a great language.
```python
print("Hello")
```
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(text, source="w3schools")
    assert decision == Decision.KEEP_TUTORIAL


def test_csv_table():
    text = """id,name,age,score
1,Alice,30,95.5
2,Bob,25,88.0
3,Charlie,35,92.1
4,David,28,85.4
5,Eve,22,99.9
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(text, path="data.csv")
    assert decision == Decision.REJECT_TABULAR


def test_weather_dataset():
    text = """date,temp,humidity,wind
2023-01-01,15.5,80,10
2023-01-02,16.0,75,12
2023-01-03,14.5,85,8
2023-01-04,15.0,82,9
2023-01-05,17.2,70,15
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(text, path="weather.csv")
    assert decision == Decision.REJECT_TABULAR


def test_system_agent_prompt():
    text = """
System prompt: You are a helpful assistant.
User: Please write a function.
Assistant: Sure, here is the function.
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(text, path="prompt.txt")
    assert decision == Decision.REJECT_PROMPT


def test_generated_metadata():
    text = """
// auto-generated by some tool
// do not edit
const config = {
    version: "1.0.0",
    build: "xyz123"
};
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(text, path="config.js")
    assert decision == Decision.REJECT_GENERATED


def test_normal_json_config():
    text = """
{
    "name": "my-project",
    "version": "1.0.0",
    "dependencies": {
        "express": "^4.17.1"
    }
}
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(text, path="package.json")
    assert decision == Decision.KEEP_CODE


def test_markdown_documentation():
    text = """
# Project Readme
This is a great project.
## Installation
Run `npm install`.
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(text, path="README.md")
    assert decision == Decision.KEEP_PROSE


def test_minified_javascript():
    text = "function a(b){return b+1;}var c=a(1);console.log(c);" * 100
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(text, path="bundle.min.js")
    assert decision == Decision.REJECT_GENERATED


def test_repetitive_log_output():
    text = """
2023-01-01 10:00:00 INFO Starting server
2023-01-01 10:00:01 INFO Server started
2023-01-01 10:00:02 DEBUG Connection received
2023-01-01 10:00:03 ERROR Failed to process
2023-01-01 10:00:04 INFO Shutting down
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(text, path="server.log")
    assert decision == Decision.REJECT_LOG


# ======================================================================
# Book Specific Tests
# ======================================================================

def test_gutenberg_header_removal():
    raw = """The Project Gutenberg eBook of Hamlet, by William Shakespeare

This eBook is for the use of anyone anywhere in the United States and most
other parts of the world at no cost and with almost no restrictions whatsoever.

*** START OF THE PROJECT GUTENBERG EBOOK HAMLET ***

ACT I

SCENE I. Elsinore. A platform before the castle.

FRANCISCO at his post. Enter to him BERNARDO.

BERNARDO
Who’s there?
"""
    cleaned = clean_gutenberg_text(raw)
    assert "*** START OF THE PROJECT GUTENBERG EBOOK" not in cleaned
    assert "This eBook is for the use of anyone" not in cleaned
    assert "ACT I" in cleaned
    assert "BERNARDO\nWho’s there?" in cleaned


def test_gutenberg_footer_removal():
    raw = """ACT V

SCENE II. A hall in the castle.

HAMLET
The rest is silence.

*** END OF THE PROJECT GUTENBERG EBOOK HAMLET ***

Section 1. General Terms of Use and Redistributing Project Gutenberg-tm
electronic works
"""
    cleaned = clean_gutenberg_text(raw)
    assert "*** END OF THE PROJECT GUTENBERG EBOOK HAMLET ***" not in cleaned
    assert "General Terms of Use and Redistributing" not in cleaned
    assert "HAMLET\nThe rest is silence." in cleaned


def test_gutenberg_preserves_legitimate_copyright_and_license():
    raw = """*** START OF THE PROJECT GUTENBERG EBOOK ESSAYS ***

CHAPTER I: ON PROPERTY AND LAW

The author examined the history of copyright in sixteenth-century England.
Under the royal license granted to the Stationers' Company, no printer could
publish without an explicit copyright registered in the company books. This
statutory license established the foundation for modern intellectual property.

CHAPTER II: CONTRACTS

A license may be revoked if either party violates the original covenant.
*** END OF THE PROJECT GUTENBERG EBOOK ESSAYS ***
"""
    cleaned = clean_gutenberg_text(raw)
    assert "history of copyright in sixteenth-century England" in cleaned
    assert "Under the royal license granted to the Stationers' Company" in cleaned
    assert "A license may be revoked" in cleaned
    assert "*** START OF THE PROJECT GUTENBERG" not in cleaned
    assert "*** END OF THE PROJECT GUTENBERG" not in cleaned


def test_catalog_page_rejection():
    catalog_text = """
Download this book in multiple formats:
- EPUB (with images)
- Plain Text UTF-8
- Kindle
QR code for mobile downloading
Bibliographic Record:
Author: Charles Dickens
Title: Great Expectations
Marc record available.
Terms of use at www.gutenberg.org
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(catalog_text, source="books")
    assert decision == Decision.REJECT_LOW_QUALITY
    assert "Catalog" in reason or "Short" in reason


def test_duplicate_book_detection():
    dedup = Deduplicator()
    book_text_1 = """
It is a truth universally acknowledged, that a single man in possession of a good fortune,
must be in want of a wife. However little known the feelings or views of such a man may be
on his first entering a neighbourhood, this truth is so well fixed in the minds of the
surrounding families, that he is considered as the rightful property of some one or other
of their daughters.
"""
    hash1 = "abc123hash"
    assert not dedup.is_duplicate(book_text_1, hash1)
    dedup.add(book_text_1, hash1)

    # Identical text
    assert dedup.is_duplicate(book_text_1, hash1)

    # Normalized duplicate with extra spaces / newlines
    book_text_2 = """
It is a truth    universally acknowledged,   that a single man in possession of a good fortune,
must be in want of a wife.   However little known the feelings or views of such a man may be
on his first entering a neighbourhood, this truth is so well fixed in the minds of the
surrounding families, that he is considered as the rightful property of some one or other
of their daughters.
"""
    hash2 = "differenthash456"
    assert dedup.is_duplicate(book_text_2, hash2)


def test_multilingual_book_preservation():
    french_text = """
Longtemps, je me suis couché de bonne heure. Parfois, à peine ma bougie éteinte,
mes yeux se fermaient si vite que je n'avais pas le temps de me dire: «Je m'endors.»
Et, une demi-heure après, la pensée qu'il était temps de chercher le sommeil m'éveillait;
je voulais poser le volume que je croyais avoir encore dans les mains et souffler ma lumière;
je n'avais pas cessé en dormant de faire des réflexions sur ce que je venais de lire,
mais ces réflexions avaient pris un tour un peu particulier; il me semblait que j'étais
moi-même ce dont parlait l'ouvrage: une église, un quatuor, la rivalité de François Ier
et de Charles-Quint.
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(french_text, source="books")
    assert decision == Decision.KEEP_PROSE


def test_poetry_preservation():
    poem_text = """
Shall I compare thee to a summer's day?
Thou art more lovely and more temperate:
Rough winds do shake the darling buds of May,
And summer's lease hath all too short a date;
Sometime too hot the eye of heaven shines,
And often is his gold complexion dimm'd;
And every fair from fair sometime declines,
By chance or nature's changing course untrimm'd;
But thy eternal summer shall not fade,
Nor lose possession of that fair thou ow'st;
Nor shall death brag thou wander'st in his shade,
When in eternal lines to time thou grow'st:
  So long as men can breathe or eyes can see,
  So long lives this, and this gives life to thee.
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(poem_text, source="books")
    assert decision == Decision.KEEP_PROSE
    b_type = classify_book_type(poem_text, title="Sonnet 18")
    assert b_type == "poetry"


def test_dialogue_and_drama_preservation():
    drama_text = """
ACT I

SCENE I. Rome. A street.

Enter FLAVIUS, MARULLUS, and certain Commoners.

FLAVIUS
Hence! home, you idle creatures get you home:
Is this a holiday? what! know you not,
Being mechanical, you ought not walk
Upon a labouring day without the sign
Of your profession? Speak, what trade art thou?

FIRST COMMONER
Why, sir, a carpenter.

MARULLUS
Where is thy leather apron and thy rule?
What dost thou with thy best apparel on?
You, sir, what trade are you?
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(drama_text, source="books")
    assert decision == Decision.KEEP_PROSE
    b_type = classify_book_type(drama_text, title="Julius Caesar")
    assert b_type == "drama"


def test_chapter_structure_preservation():
    book_text = """
CHAPTER I. DOWN THE RABBIT-HOLE

Alice was beginning to get very tired of sitting by her sister on the bank,
and of having nothing to do: once or twice she had peeped into the book her
sister was reading, but it had no pictures or conversations in it, 'and what
is the use of a book,' thought Alice 'without pictures or conversations?'

So she was considering in her own mind (as well as she could, for the hot day
made her feel very sleepy and stupid), whether the pleasure of making a
daisy-chain would be worth the trouble of getting up and picking the daisies,
when suddenly a White Rabbit with pink eyes ran close by her.

CHAPTER II. THE POOL OF TEARS

'Curiouser and curiouser!' cried Alice (she was so much surprised, that for the
moment she quite forgot how to speak good English); 'now I'm opening out like
the largest telescope that ever was! Good-bye, feet!'
"""
    classifier = DocumentClassifier()
    decision, reason, stats = classifier.classify(book_text, source="books")
    assert decision == Decision.KEEP_PROSE
    assert "CHAPTER I" in book_text
    assert "CHAPTER II" in book_text


if __name__ == "__main__":
    test_valid_python_source()
    test_valid_tutorial_prose()
    test_csv_table()
    test_weather_dataset()
    test_system_agent_prompt()
    test_generated_metadata()
    test_normal_json_config()
    test_markdown_documentation()
    test_minified_javascript()
    test_repetitive_log_output()
    test_gutenberg_header_removal()
    test_gutenberg_footer_removal()
    test_gutenberg_preserves_legitimate_copyright_and_license()
    test_catalog_page_rejection()
    test_duplicate_book_detection()
    test_multilingual_book_preservation()
    test_poetry_preservation()
    test_dialogue_and_drama_preservation()
    test_chapter_structure_preservation()
    print("All filter tests passed!")
